# Generated by Django 4.1.11 on 2024-02-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_calmsongs_audio_file_alter_calmsongs_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapturedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="captured_images/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
