# Generated by Django 4.1.11 on 2024-02-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_capturedimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capturedimage",
            name="image",
            field=models.ImageField(upload_to="captured_images/"),
        ),
    ]
